"use strict";
var TEXT_EN = {
    login: {
        "account": "Account",
        "password": "Password",
        "remember_me": "Remember Me",
        "login": "LOG IN",
        "language": "Language",
        "register": "Register",
        "forgot": "Forgot Password",
    },
    home: {
        "logout": "Log Out",
        "settings": "Settings",
        "dev": "Tus & Dev",
        "experimental": "Experimental",
        "operation": "Operation",
        "personal": "Personal",
        "management": "Management",
        "shared": "Shared",
        "admin": "System Administration",
        contact: "Contact",
        heroes: "Heroes",
        crisis: "Crisis",
        "time-management": "Time Management",
        account: "Accounting",
        crm: "CRM",
        scm: "SCM",
        app01: "Something More 01",
        app02: "Something More 02",
        app03: "Something More 03",
        app04: "Something More 04",
        app05: "Something More 05",
        workflow: "Workflow",
        "business-trip": "Business Trip",
        "traffic-fee": "Traffic Fee",
        organization: "Organization Information",
        "book-shelf": "Book Shelf",
        forms: "Forms",
        map: "Google Map",
        svg: "SVG Map",
        calendar: "Calendar",
        handwrite: "Handwrite",
        charts: "Charts",
        motion: "Motion",
        "3d-view": "3D View",
        "ui-components": "UI Components",
        "admin-contents": "Contents Management",
        "admin-permission": "Permission Management",
        "admin-users": "Users Management",
        "admin-organization": "Organization Management",
        "admin-texts": "Text Edit",
        "employees": "Employees",
    }
};
var TEXT_JA = {
    login: {
        "account": "\u30a2\u30ab\u30a6\u30f3\u30c8",
        "password": "\u30d1\u30b9\u30ef\u30fc\u30c9",
        "remember_me": "\u30ed\u30b0\u30a4\u30f3\u60c5\u5831\u3092\u4fdd\u5b58",
        "login": "\u30ed\u30b0\u30a4\u30f3",
        "language": "\u8868\u793a\u8a00\u8a9e",
        "register": "\u767b\u9332",
        "forgot": "\u30d1\u30b9\u30ef\u30fc\u30c9\u3092\u5fd8\u308c\u305f",
    },
    home: {
        "logout": "ログアウト",
        "settings": "\u8a2d\u5b9a",
        "dev": "Tuts & Dev",
        "experimental": "\u30a8\u30af\u30b9\u30da\u30ea\u30e1\u30f3\u30bf\u30eb",
        "operation": "\u30aa\u30da\u30ec\u30fc\u30b7\u30e7\u30f3",
        "personal": "\u30d1\u30fc\u30bd\u30ca\u30eb",
        "management": "\u30de\u30cd\u30fc\u30b8\u30e1\u30f3\u30c8",
        "shared": "\u5171\u901a",
        "admin": "\u30b7\u30b9\u30c6\u30e0\u7ba1\u7406",
        "contact": "コンタクト",
        "heroes": "ヒーローズ",
        "crisis": "クライシス",
        "time-management": "勤怠管理",
        "account": "会計",
        "crm": "CRM",
        "scm": "SCM",
        "app01": "サンプル 01",
        "app02": "サンプル 02",
        "app03": "サンプル 03",
        "app04": "サンプル 04",
        "app05": "サンプル 05",
        "workflow": "ワークフロー",
        "business-trip": "出張旅費精算",
        "traffic-fee": "交通費精算",
        "organization": "組織情報",
        "book-shelf": "書籍",
        "forms": "入力フォーム",
        "map": "Google Map",
        "svg": "SVG Map",
        "calendar": "カレンダー",
        "handwrite": "手書き",
        "charts": "チャート",
        "motion": "モーション",
        "3d-view": "3D View",
        "ui-components": "UI コンポーネント",
        "admin-contents": "コンテンツ管理",
        "admin-permission": "権限管理",
        "admin-users": "ユーザ管理",
        "admin-organization": "組織管理",
        "admin-texts": "テキスト編集",
        "employees": "人事台帳",
    }
};
exports.TextData = {
    en: TEXT_EN,
    ja: TEXT_JA
};
